[window]
# blur = true
dynamic_title = true
decorations = "Full"
opacity = 0.95
decorations_theme_variant = "Dark"
dimensions = { columns = 125, lines = 30 }

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Medium" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic" }
size = 11
builtin_box_drawing = false

[cursor]
style = { shape = "Block", blinking = "On" }

[mouse]
hide_when_typing = true

[terminal]
osc52 = "CopyPaste"
