-- Import CORE settings
require("core.mappings")
require("core.plugin_manager")
require("core.colors")
require("core.config")

-- Import pluggins & their settings
require("plugins.lualine")
require("plugins.bufferline")
require("plugins.neo_tree")
require("plugins.treesitter")
require("plugins.mason")
require("plugins.mason_lspconfig")
require("plugins.mason_dapconfig")
require("plugins.mason_nullls")
require("plugins.none_ls")
require("plugins.nvim_lsp")
require("plugins.autopairs")
require("plugins.luasnip")
require("plugins.lspsaga")
require("plugins.gitsigns")
require("plugins.cmp")
require("plugins.colorizer")
require("plugins.better_escape")
require("plugins.comment")
require("plugins.noice")
require("plugins.dashboard")
require("plugins.whichkey")
require("plugins.trouble")
require("plugins.toggleterm")
require("plugins.todo_comments")
require("plugins.telescope_ui_select")
require("plugins.telescope")
require("plugins.trim")
require("plugins.surround")
require("plugins.rainbow_delimiters")
require("plugins.auto_save")
require("plugins.ts_autotag")
