require("mason-lspconfig").setup {
  ensure_installed = {
    "lua_ls",
    "pyright",
    "clangd",
    "arduino_language_server",
    "rust_analyzer",
    "taplo",
    "omnisharp",
    "gopls",
    "tsserver",
    "html",
    "cssls",
    "jdtls",
    "kotlin_language_server",
    "gradle_ls",
    --TODO: Enable sqls language server, when they fix Golang errors
    "sqls",
    "bashls",
    "powershell_es",
    "dockerls",
    "jsonls",
    "marksman",
    "lemminx",
    "yamlls",
  },
  automatic_installation = true,
}
