local wk = require("which-key")

wk.register({
  ["<leader>"] = {
    f = {
      name = "Find",
      f = { "Find File" },
      b = { "Find Buffer" },
      h = { "Find Help" },
      w = { "Find Text" },
    },
    q = { "Quit" },
    w = {
      "Save",
      a = { "Save all" },
    },
    m = {
      name = "Markdown preview",
      t = { "Markdown toggle preview" },
    },
    e = { "Float file manager" },
    E = { "Float reveal file manager" },
    x = { "Close Buffer" },
    X = { "Close right Buffers" },
    s = { "Sort BufferLine tabs" },
    t = {
      name = "Trouble",
      x = { "Toggle trouble" },
      w = { "Toggle trouble workspace diagnostics" },
      d = { "Toggle trouble document diagnostics" },
      q = { "Toggle trouble quickfix" },
      l = { "Toggle trouble loclist" },
    },
    h = { "No highlight" },
    g = {
      name = "Git",
      b = { "Branches" },
      c = { "Commits" },
      d = { "Open Diffview" },
      f = { "Close Diffview" },
      s = { "Status" },
    },
    c = {
      name = "Comment",
      l = { "Comment/uncomment Line" },
    },
    ["?"] = { "Comment/uncomment block" },
    ["/"] = { "Comment/uncomment Line" },
    d = {
      name = "Debugging",
      t = { "Set breakpoint" },
      c = { "Set conditional breakpoint" },
      p = { "Set log breakpoint" },
      o = { "Step over" },
      l = { "Run last" },
      x = { "Terminate debugging" },
    },
    l = {
      name = "LSP",
      l = { "Set loclist" },
      d = { "Go to definition" },
      D = { "Hover diagnostic" },
      f = { "Format file" },
      a = { "Code actions" },
      k = { "Hover documentation" },
    },
  },
  ["<C-k>"] = { "Switch to top window" },
  ["<C-j>"] = { "Switch to bottom window" },
  ["<C-h>"] = { "Switch to left window" },
  ["<C-l>"] = { "Switch to right window" },
  ["<S-s>"] = { "Surround selected text" },
  ["<Tab>"] = { "Swich to next buffer" },
  ["<S-Tab>"] = { "Swich to previous buffer" },
  ["|"] = { "Vertical split" },
  ["\\"] = { "Horizontal split" },
  ["<F2>"] = { "Rename" },
  ["<F5>"] = { "Start/Continue debugging" },
  ["<S-F5>"] = { "Stop debugging" },
  ["<C-S-F5>"] = { "Restart debugging" },
  ["<F6>"] = { "Open compiler" },
  ["<S-F6>"] = { "Rerun compiler" },
  ["<S-F7>"] = { "Toggle compiler results" },
  ["<F10>"] = { "Step over" },
  ["<F11>"] = { "Step into" },
  ["<F12>"] = { "Step out" },
})

wk.setup({})
